name: Deploy to Azure
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
    
    - name: Create deployment package
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Creating deployment package..."
        mkdir -p deployment
        cp app_new.py deployment/
        cp requirements.txt deployment/
        cp -r src deployment/
        cp web.config deployment/
        cp packages.txt deployment/
        cd deployment
        echo "Deployment directory contents:"
        ls -la
        tar -czf ../deployment.tar.gz .
        cd ..
        echo "Created deployment.tar.gz"
        ls -la deployment.tar.gz
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'youtube-product-analyzer'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.tar.gz
        app-type: 'webapp'
        runtime: 'PYTHON|3.11'
        startup-file: 'gunicorn --bind=0.0.0.0 --timeout 600 app_new:app' 