name: Deploy to Azure
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
    
    - name: Debug - List files
      run: |
        echo "Current directory contents:"
        ls -la
        echo "src directory contents:"
        ls -la src/
    
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp app_new.py deployment/
        cp requirements.txt deployment/
        cp -r src deployment/
        cp .deployment deployment/
        cp startup.txt deployment/
        cp packages.txt deployment/
        echo "Deployment package contents:"
        ls -la deployment/
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'youtube-product-analyzer'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        app-type: 'webapp'
        runtime: 'PYTHON|3.11'
        startup-file: 'gunicorn --bind=0.0.0.0 --timeout 600 app_new:app' 