name: Deploy to Azure
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
    
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp app_new.py deployment/
        cp requirements.txt deployment/
        cp -r src deployment/
        cp .deployment deployment/
        cp startup.sh deployment/
        cp packages.txt deployment/
        cd deployment
        echo "Files in deployment directory:"
        ls -la
        zip -r ../deployment.zip .
        cd ..
        echo "Created deployment.zip"
        ls -la deployment.zip
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'youtube-product-analyzer'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.zip
        app-type: 'webapp'
        runtime: 'PYTHON|3.11'
        startup-file: 'startup.sh' 